//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Горводоканал
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Обращение.
    /// </summary>
    // *** Start programmer edit section *** (Обращение CustomAttributes)

    // *** End programmer edit section *** (Обращение CustomAttributes)
    [BusinessServer("IIS.Горводоканал.ОбращениеBS, Горводоканал(BusinessServers)", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОбращениеE", new string[] {
            "Номер as \'Номер\'",
            "Статус as \'Статус\'",
            "ДатаПоступления as \'Дата поступления\'",
            "ДатаЗакрытия as \'Дата закрытия\'",
            "ФИООбратившегося as \'ФИО\' on \'-Обратившийся\'",
            "АдресОбратившегося as \'Адрес\' on \'-Обратившийся\'",
            "ТелефонОбратившегося as \'Телефон\' on \'-Обратившийся\'",
            "Первичное as \'Первичное\'",
            "Причина as \'Причина\'",
            "Вид as \'Вид\'",
            "Тип as \'Тип\'",
            "ОтветственныйСотрудник as \'Ответственный сотрудник\'",
            "ПринявшийОператор as \'Принявший\'"})]
    [MasterViewDefineAttribute("ОбращениеE", "Причина", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ОбращениеE", "Вид", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ОбращениеE", "Тип", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ОбращениеE", "ОтветственныйСотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ОбращениеE", "ПринявшийОператор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ОбращениеL", new string[] {
            "Номер as \'Номер\'",
            "Статус as \'Статус\'",
            "ДатаПоступления as \'Дата поступления\'",
            "ДатаЗакрытия as \'Дата закрытия\'",
            "Первичное.АдресОбратившегося as \'Адрес обратившегося\'",
            "Тип.Название as \'Название\'",
            "Вид.Название as \'Название\'",
            "Причина.Название as \'Название\'"})]
    public class Обращение : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.Горводоканал.tСтатусОбращения fСтатус;
        
        private System.DateTime? fДатаПоступления;
        
        private System.DateTime? fДатаЗакрытия;
        
        private string fФИООбратившегося;
        
        private string fАдресОбратившегося;
        
        private string fТелефонОбратившегося;
        
        private IIS.Горводоканал.Сотрудник fПринявшийОператор;
        
        private IIS.Горводоканал.Обращение fПервичное;
        
        private IIS.Горводоканал.ПричинаОбращения fПричина;
        
        private IIS.Горводоканал.ВидОбращения fВид;
        
        private IIS.Горводоканал.ТипОбращения fТип;
        
        private IIS.Горводоканал.Сотрудник fОтветственныйСотрудник;
        
        // *** Start programmer edit section *** (Обращение CustomMembers)

        // *** End programmer edit section *** (Обращение CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.Номер CustomAttributes)

        // *** End programmer edit section *** (Обращение.Номер CustomAttributes)
        [DisableInsertProperty(true)]
        [NotNull()]
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.Номер Get start)

                // *** End programmer edit section *** (Обращение.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Обращение.Номер Get end)

                // *** End programmer edit section *** (Обращение.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.Номер Set start)

                // *** End programmer edit section *** (Обращение.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Обращение.Номер Set end)

                // *** End programmer edit section *** (Обращение.Номер Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.Статус CustomAttributes)

        // *** End programmer edit section *** (Обращение.Статус CustomAttributes)
        public virtual IIS.Горводоканал.tСтатусОбращения Статус
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.Статус Get start)

                // *** End programmer edit section *** (Обращение.Статус Get start)
                IIS.Горводоканал.tСтатусОбращения result = this.fСтатус;
                // *** Start programmer edit section *** (Обращение.Статус Get end)

                // *** End programmer edit section *** (Обращение.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.Статус Set start)

                // *** End programmer edit section *** (Обращение.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Обращение.Статус Set end)

                // *** End programmer edit section *** (Обращение.Статус Set end)
            }
        }
        
        /// <summary>
        /// ДатаПоступления.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.ДатаПоступления CustomAttributes)

        // *** End programmer edit section *** (Обращение.ДатаПоступления CustomAttributes)
        public virtual System.DateTime? ДатаПоступления
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.ДатаПоступления Get start)

                // *** End programmer edit section *** (Обращение.ДатаПоступления Get start)
                System.DateTime? result = this.fДатаПоступления;
                // *** Start programmer edit section *** (Обращение.ДатаПоступления Get end)

                // *** End programmer edit section *** (Обращение.ДатаПоступления Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.ДатаПоступления Set start)

                // *** End programmer edit section *** (Обращение.ДатаПоступления Set start)
                this.fДатаПоступления = value;
                // *** Start programmer edit section *** (Обращение.ДатаПоступления Set end)

                // *** End programmer edit section *** (Обращение.ДатаПоступления Set end)
            }
        }
        
        /// <summary>
        /// ДатаЗакрытия.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.ДатаЗакрытия CustomAttributes)

        // *** End programmer edit section *** (Обращение.ДатаЗакрытия CustomAttributes)
        public virtual System.DateTime? ДатаЗакрытия
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.ДатаЗакрытия Get start)

                // *** End programmer edit section *** (Обращение.ДатаЗакрытия Get start)
                System.DateTime? result = this.fДатаЗакрытия;
                // *** Start programmer edit section *** (Обращение.ДатаЗакрытия Get end)

                // *** End programmer edit section *** (Обращение.ДатаЗакрытия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.ДатаЗакрытия Set start)

                // *** End programmer edit section *** (Обращение.ДатаЗакрытия Set start)
                this.fДатаЗакрытия = value;
                // *** Start programmer edit section *** (Обращение.ДатаЗакрытия Set end)

                // *** End programmer edit section *** (Обращение.ДатаЗакрытия Set end)
            }
        }
        
        /// <summary>
        /// ФИООбратившегося.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.ФИООбратившегося CustomAttributes)

        // *** End programmer edit section *** (Обращение.ФИООбратившегося CustomAttributes)
        [StrLen(150)]
        [NotNull()]
        public virtual string ФИООбратившегося
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.ФИООбратившегося Get start)

                // *** End programmer edit section *** (Обращение.ФИООбратившегося Get start)
                string result = this.fФИООбратившегося;
                // *** Start programmer edit section *** (Обращение.ФИООбратившегося Get end)

                // *** End programmer edit section *** (Обращение.ФИООбратившегося Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.ФИООбратившегося Set start)

                // *** End programmer edit section *** (Обращение.ФИООбратившегося Set start)
                this.fФИООбратившегося = value;
                // *** Start programmer edit section *** (Обращение.ФИООбратившегося Set end)

                // *** End programmer edit section *** (Обращение.ФИООбратившегося Set end)
            }
        }
        
        /// <summary>
        /// АдресОбратившегося.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.АдресОбратившегося CustomAttributes)

        // *** End programmer edit section *** (Обращение.АдресОбратившегося CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string АдресОбратившегося
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.АдресОбратившегося Get start)

                // *** End programmer edit section *** (Обращение.АдресОбратившегося Get start)
                string result = this.fАдресОбратившегося;
                // *** Start programmer edit section *** (Обращение.АдресОбратившегося Get end)

                // *** End programmer edit section *** (Обращение.АдресОбратившегося Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.АдресОбратившегося Set start)

                // *** End programmer edit section *** (Обращение.АдресОбратившегося Set start)
                this.fАдресОбратившегося = value;
                // *** Start programmer edit section *** (Обращение.АдресОбратившегося Set end)

                // *** End programmer edit section *** (Обращение.АдресОбратившегося Set end)
            }
        }
        
        /// <summary>
        /// ТелефонОбратившегося.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.ТелефонОбратившегося CustomAttributes)

        // *** End programmer edit section *** (Обращение.ТелефонОбратившегося CustomAttributes)
        [StrLen(150)]
        public virtual string ТелефонОбратившегося
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.ТелефонОбратившегося Get start)

                // *** End programmer edit section *** (Обращение.ТелефонОбратившегося Get start)
                string result = this.fТелефонОбратившегося;
                // *** Start programmer edit section *** (Обращение.ТелефонОбратившегося Get end)

                // *** End programmer edit section *** (Обращение.ТелефонОбратившегося Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.ТелефонОбратившегося Set start)

                // *** End programmer edit section *** (Обращение.ТелефонОбратившегося Set start)
                this.fТелефонОбратившегося = value;
                // *** Start programmer edit section *** (Обращение.ТелефонОбратившегося Set end)

                // *** End programmer edit section *** (Обращение.ТелефонОбратившегося Set end)
            }
        }
        
        /// <summary>
        /// Обращение.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.ПринявшийОператор CustomAttributes)

        // *** End programmer edit section *** (Обращение.ПринявшийОператор CustomAttributes)
        [PropertyStorage(new string[] {
                "ПринявшийОператор"})]
        [NotNull()]
        public virtual IIS.Горводоканал.Сотрудник ПринявшийОператор
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.ПринявшийОператор Get start)

                // *** End programmer edit section *** (Обращение.ПринявшийОператор Get start)
                IIS.Горводоканал.Сотрудник result = this.fПринявшийОператор;
                // *** Start programmer edit section *** (Обращение.ПринявшийОператор Get end)

                // *** End programmer edit section *** (Обращение.ПринявшийОператор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.ПринявшийОператор Set start)

                // *** End programmer edit section *** (Обращение.ПринявшийОператор Set start)
                this.fПринявшийОператор = value;
                // *** Start programmer edit section *** (Обращение.ПринявшийОператор Set end)

                // *** End programmer edit section *** (Обращение.ПринявшийОператор Set end)
            }
        }
        
        /// <summary>
        /// Обращение.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.Первичное CustomAttributes)

        // *** End programmer edit section *** (Обращение.Первичное CustomAttributes)
        [PropertyStorage(new string[] {
                "Первичное"})]
        public virtual IIS.Горводоканал.Обращение Первичное
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.Первичное Get start)

                // *** End programmer edit section *** (Обращение.Первичное Get start)
                IIS.Горводоканал.Обращение result = this.fПервичное;
                // *** Start programmer edit section *** (Обращение.Первичное Get end)

                // *** End programmer edit section *** (Обращение.Первичное Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.Первичное Set start)

                // *** End programmer edit section *** (Обращение.Первичное Set start)
                this.fПервичное = value;
                // *** Start programmer edit section *** (Обращение.Первичное Set end)

                // *** End programmer edit section *** (Обращение.Первичное Set end)
            }
        }
        
        /// <summary>
        /// Обращение.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.Причина CustomAttributes)

        // *** End programmer edit section *** (Обращение.Причина CustomAttributes)
        [PropertyStorage(new string[] {
                "Причина"})]
        public virtual IIS.Горводоканал.ПричинаОбращения Причина
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.Причина Get start)

                // *** End programmer edit section *** (Обращение.Причина Get start)
                IIS.Горводоканал.ПричинаОбращения result = this.fПричина;
                // *** Start programmer edit section *** (Обращение.Причина Get end)

                // *** End programmer edit section *** (Обращение.Причина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.Причина Set start)

                // *** End programmer edit section *** (Обращение.Причина Set start)
                this.fПричина = value;
                // *** Start programmer edit section *** (Обращение.Причина Set end)

                // *** End programmer edit section *** (Обращение.Причина Set end)
            }
        }
        
        /// <summary>
        /// Обращение.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.Вид CustomAttributes)

        // *** End programmer edit section *** (Обращение.Вид CustomAttributes)
        [PropertyStorage("Вид")]
        [TypeUsage(new string[] {
                "IIS.Горводоканал.ВидОбращения",
                "IIS.Горводоканал.Сотрудник"})]
        public virtual IIS.Горводоканал.ВидОбращения Вид
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.Вид Get start)

                // *** End programmer edit section *** (Обращение.Вид Get start)
                IIS.Горводоканал.ВидОбращения result = this.fВид;
                // *** Start programmer edit section *** (Обращение.Вид Get end)

                // *** End programmer edit section *** (Обращение.Вид Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.Вид Set start)

                // *** End programmer edit section *** (Обращение.Вид Set start)
                this.fВид = value;
                // *** Start programmer edit section *** (Обращение.Вид Set end)

                // *** End programmer edit section *** (Обращение.Вид Set end)
            }
        }
        
        /// <summary>
        /// Обращение.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.Тип CustomAttributes)

        // *** End programmer edit section *** (Обращение.Тип CustomAttributes)
        [PropertyStorage(new string[] {
                "Тип"})]
        public virtual IIS.Горводоканал.ТипОбращения Тип
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.Тип Get start)

                // *** End programmer edit section *** (Обращение.Тип Get start)
                IIS.Горводоканал.ТипОбращения result = this.fТип;
                // *** Start programmer edit section *** (Обращение.Тип Get end)

                // *** End programmer edit section *** (Обращение.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.Тип Set start)

                // *** End programmer edit section *** (Обращение.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Обращение.Тип Set end)

                // *** End programmer edit section *** (Обращение.Тип Set end)
            }
        }
        
        /// <summary>
        /// Обращение.
        /// </summary>
        // *** Start programmer edit section *** (Обращение.ОтветственныйСотрудник CustomAttributes)

        // *** End programmer edit section *** (Обращение.ОтветственныйСотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "ОтветственныйСотрудник"})]
        public virtual IIS.Горводоканал.Сотрудник ОтветственныйСотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Обращение.ОтветственныйСотрудник Get start)

                // *** End programmer edit section *** (Обращение.ОтветственныйСотрудник Get start)
                IIS.Горводоканал.Сотрудник result = this.fОтветственныйСотрудник;
                // *** Start programmer edit section *** (Обращение.ОтветственныйСотрудник Get end)

                // *** End programmer edit section *** (Обращение.ОтветственныйСотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Обращение.ОтветственныйСотрудник Set start)

                // *** End programmer edit section *** (Обращение.ОтветственныйСотрудник Set start)
                this.fОтветственныйСотрудник = value;
                // *** Start programmer edit section *** (Обращение.ОтветственныйСотрудник Set end)

                // *** End programmer edit section *** (Обращение.ОтветственныйСотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОбращениеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбращениеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбращениеE", typeof(IIS.Горводоканал.Обращение));
                }
            }
            
            /// <summary>
            /// "ОбращениеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбращениеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбращениеL", typeof(IIS.Горводоканал.Обращение));
                }
            }
        }
    }
}
