//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Горводоканал
{
    using ICSSoft.STORMNET;
    using System;
    using System.Xml;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Обращение BS.
    /// </summary>
    // *** Start programmer edit section *** (ОбращениеBS CustomAttributes)

    // *** End programmer edit section *** (ОбращениеBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ОбращениеBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (ОбращениеBS CustomMembers)

        // *** End programmer edit section *** (ОбращениеBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateОбращение CustomAttributes)

        // *** End programmer edit section *** (OnUpdateОбращение CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateОбращение(IIS.Горводоканал.Обращение UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateОбращение)
            if (UpdatedObject .GetStatus ()== ObjectStatus.Created )
            {
                UpdatedObject.ДатаПоступления = DateTime.Now;
            }

            if (UpdatedObject.GetStatus() == ObjectStatus.Altered && UpdatedObject .Статус ==  tСтатусОбращения.Закрыто)
            {
                UpdatedObject.ДатаЗакрытия = DateTime.Now;
            }
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateОбращение)
        }
    }
}
